baseURL = "http://brianolliff.com/"
languageCode = "en-us"
title = "Brian Olliff"

theme = "ananke"

resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 7 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "Where I put my random thoughts"
  facebook = ""
  twitter = "https://twitter.com/beardsengaming"
  instagram = ""
  youtube = "https://www.youtube.com/channel/UCTSO4xg2aIkKwILGBKOn37Q"
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  twitch = "https://twitch.tv/beardsengaming"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2