# Timer Theme

baseURL = "https://brianolliff.com/"
languageCode = "en-us"
title = "Brian Olliff"
theme = "timer"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Navbar Menus
[[menu.main]]
name    = "Home"
url     = "/"
weight  = 1
[[menu.main]]
name    = "About"
url     = "about"
weight  = 2
# [[menu.main]]
# name    = "Gallery"
# url     = "gallery"
# weight  = 3
[[menu.main]]
name    = "Blog"
url     = "posts"
weight  = 4
[[menu.main]]
name    = "Contact"
url     = "contact"
weight  = 5

# Site Params
[params]
home = "Home"
logo = "images/brianolliff_website_logo.png"
dateFormat = "6 January 2006"
# Meta data
description = "Airspace Hugo theme"
author = "Themefisher"
# Google Analitycs
googleAnalitycsID = "Your ID"
# contact form action
contactFormAction = "https://formspree.io/f/meqvrvjd" # contact form works with https://formspree.io

# Banner Section
[params.banner]
enable  = true
bgImage = "images/slider.jpg"
heading = "Hi there.  I'm Brian and I'm a"
description = "Over 15 years of IT/Cyber Security experience, an avid Sci-Fi fan, Dungeons & Dragons DM, content creator, and all around nerd.  Here is my stuff"
# button
# btn     = true
# btnText = "Download More"
# btnURL  = "https://themefisher.com/"

# flip text
[[params.banner.flipText]]
title   = "CREATOR"
[[params.banner.flipText]]
title   = "SECURITY PROFESSIONAL"
[[params.banner.flipText]]
title   = "GAMER"
[[params.banner.flipText]]
title   = "D&D DM"

# Homepage About Section
[params.about]
enable  = true
title   = "ABOUT ME"
content = "Hi there, I'm Brian - an IT professional from the Southeast US.  I've been doing IT work in various forms for the past 15-20 years or so and am currently a Cyber Security Manager.<br> <br> When I'm not working, I'm either creating content for this site or YouTube, or working on various aspects of my D&D games, which are also streamed on Twitch.  Occasionally there's some camping thrown in there as well.  Oh, and I love scotch."
image   = "images/about/about.jpg"

# Call to Action
[params.cta]
enable  = true
title   = "Would you like to know more?"
content = "Come on, I know you got that reference, Rico.  <br><br>Well, even if you don't, click that button below to contact me and ask me anything!"
btnText = "Contact me"
btnURL  = "/contact"

# Portfolio Section On Homepage
[params.portfolio]
enable  = false
title   = "Latest Works"
subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

# social icon
[[params.socialIcon]]
icon = "ion-social-twitter"
url = "https://twitter.com/beardsengaming"

[[params.socialIcon]]
icon = "ion-social-youtube"
url = "https://www.youtube.com/channel/UCTSO4xg2aIkKwILGBKOn37Q"

[[params.socialIcon]]
icon = "ion-social-twitch"
url = "https://twitch.tv/beardsengaming"

[[params.socialIcon]]
icon = "ion-social-linkedin"
url = "https://www.linkedin.com/in/brianolliff/"
